"""add missing customer fields

Revision ID: 501917932ef8
Revises: 37c65dad6900
Create Date: 2025-08-22 09:07:21.990147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501917932ef8'
down_revision = '37c65dad6900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=100), nullable=True))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_logs_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_logs_visit_id'), ['visit_id'], unique=False)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_customer_id'))

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_logs_visit_id'))
        batch_op.drop_index(batch_op.f('ix_service_logs_equipment_id'))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_customer_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('contact_person')
        batch_op.drop_column('city')
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
