"""Add equipment, visits, service_logs

Revision ID: bf7db56ce535
Revises: 501917932ef8
Create Date: 2025-08-22 09:18:41.253728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf7db56ce535'
down_revision = '501917932ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('installed_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('install_date')
        batch_op.drop_column('model')

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('technician')

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.drop_column('log_date')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('install_date', sa.DATE(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('installed_at')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
