"""add visits_per_year and start_date to customer

Revision ID: e3122ba67342
Revises: caaa87d41e30
Create Date: 2025-08-22 12:55:27.962162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3122ba67342'
down_revision = 'caaa87d41e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visits_per_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('start_date')
        batch_op.drop_column('visits_per_year')

    # ### end Alembic commands ###
