"""add materials, material usage, employees, route choices, photos

Revision ID: ed08a9a8007b
Revises: bf7db56ce535
Create Date: 2025-08-22 10:41:54.752276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed08a9a8007b'
down_revision = 'bf7db56ce535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('active_ingredient', sa.String(length=100), nullable=True),
    sa.Column('standard_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_email', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('selected_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_choices_customer_id'), ['customer_id'], unique=False)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_visit_id'), ['visit_id'], unique=False)

    op.create_table('material_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_log_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['service_log_id'], ['service_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_usage_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_usage_service_log_id'), ['service_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_usage_service_log_id'))
        batch_op.drop_index(batch_op.f('ix_material_usage_material_id'))

    op.drop_table('material_usage')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_visit_id'))

    op.drop_table('photos')
    with op.batch_alter_table('route_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_choices_customer_id'))

    op.drop_table('route_choices')
    op.drop_table('materials')
    op.drop_table('employees')
    # ### end Alembic commands ###
