param(
    [string]$DriveShare,
    [string]$DriveLetter,
    [string]$NasPath,
    [string]$SourcePath = (Get-Location).Path,
    [switch]$IncludeDockerCompose = $true,
    [string]$DatabaseUrl,
    [int]$Port = 8000,
    [switch]$DryRun
)

function Write-Log([string]$m) { Write-Host "[deploy] $m" }
function Confirm([string]$m) { return (Read-Host "$m [y/N]").Trim().ToLower() -eq 'y' }

if ($DriveShare -and $DriveLetter) {
    Write-Log "Mapping drive $DriveLetter -> $DriveShare"
    net use $DriveLetter $DriveShare /persistent:yes | Out-Null
    if (-not $NasPath) { $NasPath = "$DriveLetter\BSK_Service_App" }
}

if (-not $NasPath) {
    Write-Host "NAS path not provided. Example: -NasPath 'Z:\\BSK_Service_App' or provide -DriveShare and -DriveLetter." -ForegroundColor Yellow
    exit 1
}

$src = Resolve-Path -Path $SourcePath | Select-Object -ExpandProperty Path
$dst = $NasPath

Write-Log "Source: $src"
Write-Log "Destination: $dst"

if ($DryRun) { Write-Log "DRY RUN: no files will be copied" }

if (-not (Test-Path $dst)) {
    Write-Log "Creating destination path $dst"
    if (-not $DryRun) { New-Item -ItemType Directory -Force -Path $dst | Out-Null }
}

# Files and directories to copy (robocopy will mirror by default)
$excludeDirs = @('.git', '.venv', 'venv', 'node_modules', 'frontend\node_modules', '.github', '.vscode', 'dist')

Write-Log "Preparing to copy project to NAS. This will mirror the repository to the NAS path."
Write-Log "Excluded directories: $($excludeDirs -join ', ')"

# Build robocopy command
$robocopyCmd = "robocopy `"$src`" `"$dst`" /MIR /MT:8 /NFL /NDL /NP /R:2 /W:2"
foreach ($d in $excludeDirs) { $robocopyCmd += " /XD `"$src\$d`"" }

Write-Log "Robocopy command: $robocopyCmd"
if (-not $DryRun) {
    Write-Log "Starting file copy (this may take a while)"
    cmd.exe /c $robocopyCmd | Write-Host
} else { Write-Log "Dry run: skipping robocopy" }

# Ensure uploads directory exists on NAS so docker bind mounts succeed
$uploadsPath = Join-Path $dst 'backend\static\uploads'
if (-not (Test-Path $uploadsPath)) {
    Write-Log "Creating uploads directory at $uploadsPath"
    if (-not $DryRun) { New-Item -ItemType Directory -Force -Path $uploadsPath | Out-Null }
} else { Write-Log "Uploads directory already exists at $uploadsPath" }

# Copy docker-compose.prod.yml and .env.example explicitly if requested
if ($IncludeDockerCompose) {
    $filesToCopy = @('docker-compose.prod.yml', '.env.example')
    foreach ($f in $filesToCopy) {
        $srcFile = Join-Path $src $f
        $dstFile = Join-Path $dst $f
        if (Test-Path $srcFile) {
            Write-Log "Copying $f to NAS"
            if (-not $DryRun) { Copy-Item -Path $srcFile -Destination $dstFile -Force }
        } else { Write-Log "Skipping $f: not found in source" }
    }
}

# If user provided a DATABASE_URL, create a .env on the NAS with safe defaults
if ($DatabaseUrl) {
    $envFile = Join-Path $dst '.env'
    Write-Log "Writing .env to $envFile (contains DATABASE_URL). Do NOT commit this file to git."
    if (-not $DryRun) {
        @(
            "# Generated by deploy_to_nas.ps1 — edit values on the NAS before starting services",
            "SECRET_KEY=change-me-please-replace",
            "DATABASE_URL=$DatabaseUrl",
            "FLASK_APP=app.py",
            "PYTHONPATH=/app",
            "PORT=$Port"
        ) | Out-File -Encoding UTF8 -FilePath $envFile
    }
}

Write-Log "Copy finished. Next steps (run on the NAS via SSH or DSM Terminal):"
Write-Host "1) cd $dst"
Write-Host "2) (optional) edit .env and set real secrets: vi .env or use DSM File Station"
Write-Host "3) Start with docker-compose (recommended):"
Write-Host "   docker-compose -f docker-compose.prod.yml up -d --build"
Write-Host "   Follow backend logs: docker-compose -f docker-compose.prod.yml logs -f backend"

Write-Log "Notes for beginners:"
Write-Host "- If you have never used the NAS shell before, open the DSM Control Panel > Terminal & SNMP to enable the terminal, or use File Station to copy and edit files."
Write-Host "- If you mapped a drive (Z:), you can also run the docker-compose command from the NAS itself — many Synology setups require running docker-compose inside the NAS (SSH)."
Write-Host "- If you prefer the script to also run docker-compose remotely, tell me and I will add optional SSH execution (requires an SSH key)."

Write-Log "Done. If you want, I can update this script to also push only changed files, or to run docker-compose on the NAS via SSH."
else { & $PythonExe -m flask db upgrade -d ..\migrations }

Write-Log "Starting application"
Set-Location $dst
if ($CreateVenv) {
    $waitress = Join-Path $dst '.venv\Scripts\waitress-serve.exe'
    if (Test-Path $waitress) { Start-Process -FilePath $waitress -ArgumentList "--listen=*:$Port backend.app:app" }
    else { Start-Process -FilePath (Join-Path $dst '.venv\Scripts\python.exe') -ArgumentList "-m backend.app" }
} else { Start-Process -FilePath $PythonExe -ArgumentList "-m backend.app" }

Write-Log "Deploy finished"

.SYNOPSIS
  Deploy the project to a local NAS share (Windows PowerShell).

.DESCRIPTION
  Copies repository files to a NAS path, optionally maps a drive, creates
  a Python virtual environment on the target, installs requirements,
  writes a minimal .env (if DATABASE_URL provided), runs DB migrations
  and attempts to start the app (waitress if installed, otherwise python).

  Designed for manual, local testing. Do NOT store secrets in the repo
  — the script will create a `.env` file on the NAS only if you pass
  the `-DatabaseUrl` parameter.

.EXAMPLE
  # Map drive, copy and deploy
  .\deploy_to_nas.ps1 -DriveShare "\\NAS\share" -DriveLetter Z -NasPath "Z:\BSK_Service_App" -CreateVenv

.EXAMPLE
  # Deploy to an already-mounted path and provide DB URL
  .\deploy_to_nas.ps1 -NasPath "Z:\BSK_Service_App" -DatabaseUrl "postgresql://user:pw@db:5432/dbname" -CreateVenv
#>

param(
    [string]$DriveShare,
    [string]$DriveLetter,
    [string]$NasPath,
    [switch]$CreateVenv,
    [string]$PythonExe = 'python',
    [string]$DatabaseUrl,
    [int]$Port = 8000
)

function Write-Log($msg){ Write-Host "[deploy] $msg" }

if ($DriveShare -and $DriveLetter) {
    Write-Log "Mapping drive $DriveLetter -> $DriveShare"
    net use $DriveLetter $DriveShare /persistent:yes | Out-Null
    if (-not $NasPath) { $NasPath = "$DriveLetter\BSK_Service_App" }
}

if (-not $NasPath) {
    Write-Host "NAS path not provided. Example: -NasPath 'Z:\\BSK_Service_App' or provide -DriveShare and -DriveLetter." -ForegroundColor Yellow
    exit 1
}

$src = (Get-Location).Path
$dst = $NasPath

Write-Log "Source: $src"
Write-Log "Destination: $dst"

if (-not (Test-Path $dst)) {
    Write-Log "Creating destination path $dst"
    New-Item -ItemType Directory -Force -Path $dst | Out-Null
}

# Copy files using robocopy and exclude common heavy or sensitive dirs
$excludeDirs = @('.git', '.venv', 'node_modules', 'frontend\node_modules', '.github', '.vscode', 'venv', 'dist')

Write-Log "Copying repository to NAS (this may take a while). Excluding: $($excludeDirs -join ', ')"

$robocopyCmd = "robocopy `"$src`" `"$dst`" /MIR /MT:8 /NFL /NDL /NP /R:2 /W:2"

foreach ($d in $excludeDirs) { $robocopyCmd += " /XD `"$src\$d`"" }

Write-Log $robocopyCmd
cmd.exe /c $robocopyCmd | Write-Host

# Create virtual environment on NAS if requested
if ($CreateVenv) {
    $venvPath = Join-Path $dst '.venv'
    if (-not (Test-Path $venvPath)) {
        Write-Log "Creating virtual environment at $venvPath"
        & $PythonExe -m venv $venvPath
    } else {
        Write-Log "Virtual environment already exists at $venvPath"
    }

    $activate = Join-Path $venvPath 'Scripts\Activate.ps1'
    Write-Log "Activating venv and installing dependencies"
    # dot-source the Activate.ps1 so the session inherits the venv variables
    . $activate
    Set-Location $dst
    $req = Join-Path $dst 'requirements.txt'
    if (Test-Path $req) {
        & $venvPath\Scripts\python.exe -m pip install --upgrade pip
        & $venvPath\Scripts\python.exe -m pip install -r $req
    } else {
        Write-Log "No requirements.txt found at $req — skipping pip install"
    }
} else {
    Write-Log "Skipping venv creation. Ensure target host has required Python env and deps."
}

# Write .env on NAS if DATABASE_URL provided
if ($DatabaseUrl) {
    $envPath = Join-Path $dst '.env'
    Write-Log "Writing .env to $envPath (contains DATABASE_URL). Ensure file is secured and not committed."
    "DATABASE_URL=$DatabaseUrl" | Out-File -Encoding UTF8 -FilePath $envPath
    "FLASK_APP=app.py" | Out-File -Encoding UTF8 -FilePath $envPath -Append
    "PYTHONPATH=$dst" | Out-File -Encoding UTF8 -FilePath $envPath -Append
}

# Run migrations
Write-Log "Running database migrations (if Flask-Migrate is configured)."
Push-Location (Join-Path $dst 'backend')
try {
    if ($CreateVenv) {
        $venvPython = Join-Path $dst '.venv\Scripts\python.exe'
        $env:PYTHONPATH = $dst
        $env:FLASK_APP = 'app.py'
        & $venvPython -m flask db upgrade -d ..\migrations
    } else {
        # run with host python
        $env:PYTHONPATH = $dst
        $env:FLASK_APP = 'app.py'
        & $PythonExe -m flask db upgrade -d ..\migrations
    }
} catch {
    Write-Host "Warning: migrations failed — check output above. You can run migrations manually on the NAS." -ForegroundColor Yellow
}
finally { Pop-Location }

# Start application
Write-Log "Starting application on port $Port"
Push-Location $dst
    if ($CreateVenv) {
        $waitressExe = Join-Path $dst '.venv\Scripts\waitress-serve.exe'
        if (Test-Path $waitressExe) {
            Write-Log "Starting with waitress"
            Start-Process -FilePath $waitressExe -ArgumentList "--listen=*:$Port backend.app:app" -NoNewWindow
        } else {
            Write-Log "waitress not installed in venv, falling back to 'python -m backend.app'"
            $py = Join-Path $dst '.venv\Scripts\python.exe'
            Start-Process -FilePath $py -ArgumentList "-m backend.app" -NoNewWindow
        }
    } else {
        Write-Log "Starting with host python"
        Start-Process -FilePath $PythonExe -ArgumentList "-m backend.app" -NoNewWindow
    }
Pop-Location

Write-Log "Deploy script finished. Check logs and the NAS-hosted app. For production use a proper service wrapper (nssm/systemd) and secure secrets storage."
